# Generated by Django 5.0.2 on 2024-03-02 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_propertyregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyregistration',
            name='area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertyregistration',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.district'),
        ),
        migrations.AlterField(
            model_name='propertyregistration',
            name='taluk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.taluk'),
        ),
        migrations.AlterField(
            model_name='propertyregistration',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.village'),
        ),
    ]
