# Generated by Django 5.0.2 on 2024-03-04 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_alter_propertyregistration_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('property_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geolocations', to='API.propertyregistration')),
            ],
        ),
    ]
