# Generated by Django 5.0.2 on 2024-02-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_devicetype_alter_device_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
