# Generated by Django 5.0.2 on 2024-03-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_geolocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyregistration',
            name='property_id',
            field=models.CharField(max_length=100),
        ),
    ]
