# Generated by Django 5.0.2 on 2024-03-12 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_alter_propertyregistration_property_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.customer')),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.device')),
                ('geolocation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.geolocation')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.propertyregistration')),
            ],
        ),
    ]
