# Generated by Django 5.0.2 on 2024-03-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_remove_propertydevice_device_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydevice',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='propertydevicedevice',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
