# Generated by Django 4.0.6 on 2024-04-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_propertydevice_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('battery_status', models.CharField(default='', max_length=100)),
                ('device_status', models.BooleanField(default=False)),
                ('device_log', models.CharField(max_length=100)),
                ('device_lat', models.CharField(max_length=100)),
                ('device_gforce', models.CharField(max_length=100)),
            ],
        ),
    ]
